### ISSUE TITLE
Suggestions & Feedback

### ISSUE THREAD

**Issue by JoshuaFern** [sharkwouter/minigalaxy#132]
### Suggestions & Feedback
Hello, I'm relatively new to minigalaxy and I wanted to note down some of my first impressions of the software while everything's still fresh in my mind:
- On each game's menu consider adding a link to [gogdb](https://www.gogdb.org/) alongside the official store. 
- On the README it states: `Features not in Minigalaxy: Installing games meant for other platforms`, this wording is ambiguous and could be interpreted as meaning Windows games are not supported. We should clarify that other online storefronts are not supported.
- Consider allowing users to set a custom directory to cache installers, because you might want to keep your games on your SSD but cache the installers on spinning rust.
- Windows games ought not to install automatically after the download completes, else you end up with bothersome windows popping up when you least expect them. The download stage and the installation stage should each be manually initiated by the user - though it would be fantastic if the installation could be completed automatically in the background instead. Maybe with some AutoHotkey magic?
- Enable us to use our existing and cached installers to install games, and use minigalaxy without being logged in.
- Enable support for downloading goodies.
- I thought at first there was no downloads on the website, but I figured out it's a dropdown under `Other distributions`. Consider making it more obvious, I think most of us are looking for big highlighted words that say download.
- The About > Credits page should include contributors.
- Ability to hide games.
- GOG Connect alerts.
- Download throttling limits.

That's all for now, I'll see about investigating these further tomorrow :)

**Comment by sharkwouter** [comment]
Thanks for the feedback and suggestions! I'll try to address them in the way I currently can. I think some of them should have their own issues, so they can actually be worked on individually, because there are some good ideas here. There are also some which I don't quite understand or I'm not sure about. I'll address them below.

- I don't know gogdb tbh. Does it provide any information which is missing in the store page?
- The feedback on the README will be fixed up. Not being able to install Windows games is exactly what it meant, but the next release will have support for that.
- There is a feature request for allowing to change the cache directory. That's issue #132.
- Automating installing Windows games has proven to be quite hard, which is why the current solution was chosen. I wish innoextract was able to extract all Windows games, but it doesn't work for most of them, unfortunately. I think using autohotkey would be very visible to the user and wouldn't work in wayland. I'm not sure if I like the idea of making the user click another time to get the installer.
- You can actually make Minigalaxy keep the installers in settings. It also has an offline mode, which triggers if no connection can be made to the API. I guess you mean that you'd also like to be able to use Minigalaxy without ever logging in?
- We should make another issue for downloading goodies.
- Yeah, the website is a bit of an afterthought. It could use some work. I'm not a web designer, though :/
- The point about the credits is a really good idea. I'll get on that now.
- I've actually denied a pull request which tried to implement hiding games before. I wasn't really able to figure out a good way to make the user able to unhide games again without major UI changes.
- I'm not familiar with GOG Connect alerts, could you explain them?
- I've not looking into throttling or limits at all. I think this would be tough to implement.

**Comment by sharkwouter** [comment]
I've updated the about page to include the contributors and translators. I hope I've not forgotten anyone.

**Comment by JoshuaFern** [comment]
> I don't know gogdb tbh. Does it provide any information which is missing in the store page?

Yup, it displays a lot of useful metadata and links akin to SteamDB.
* View price history
* Direct download links to games (must be logged in I assume)
* Full version history & changelog
* Screenshots and Videos
* Open Source https://github.com/Yepoleb/gogdb

>  Automating installing Windows games has proven to be quite hard, which is why the current solution was chosen. I wish innoextract was able to extract all Windows games, but it doesn't work for most of them, unfortunately. I think using autohotkey would be very visible to the user and wouldn't work in wayland. I'm not sure if I like the idea of making the user click another time to get the installer.

I had this crazy idea that you might be able to create a hidden WINE virtual desktop and do the autohotkey tasks in there, no idea if it would actually work. Surely this is a solved problem that another project has figured out somewhere? More investigation is needed.

I have terrible internet though and who knows what I'll be doing once the download finishes. Imagine starting a download hours ago, and now a GOG installer pops up right as you're playing a game. That's why the user ought to start that process manually, not unlike how Steam only starts the first-time setup process when the user attempts to play the game. 

> You can actually make Minigalaxy keep the installers in settings. It also has an offline mode, which triggers if no connection can be made to the API. I guess you mean that you'd also like to be able to use Minigalaxy without ever logging in?

Yeah, it would be nice to skip the login entirely. I mean GOG games are DRM free, isn't that kind of the point? ;)

> We should make another issue for downloading goodies.

#133 

> Yeah, the website is a bit of an afterthought. It could use some work. I'm not a web designer, though :/

It's not terrible, let's improve it!

> I've actually denied a pull request which tried to implement hiding games before. I wasn't really able to figure out a good way to make the user able to unhide games again without major UI changes.

Sounds like that PR was unfinished if there was no way to unhide the games, here's two ways:
- The lazy way, simply add an 'unhide all' button.
- The feature-creep way, create an entire category system not unlike the one that already exists on GOG's website. If you could pull existing categories from the GOG website that would be even better :)

> I'm not familiar with GOG Connect alerts, could you explain them?

Sure, GOG Connect is a service that allows you to claim a DRM-Free copy of games you already own on Steam. It would be nice if users could opt to receive alerts when these offers are available: https://www.gog.com/connect

> I've not looking into throttling or limits at all. I think this would be tough to implement.

This again ties into my slow internet, while downloading a game at full speed everything else online suffers. I use this feature on any application that offers it.

**Comment by JoshuaFern** [comment]
Just wanted to add that Minigalaxy has an edge over more general applications like Lutris in that it can laser focus and create a lot of great features to enhance the GOG experience as much as possible. That's what we should focus on, being the best at that one thing.

**Comment by sharkwouter** [comment]
Ah okay, the slow internet connection explains a lot. That's not really something I run into, but there are probably many more people who do. A separate issue for that may be good, although I have no idea how I'd solve that yet.

The main priority for Minigalaxy is ease of use. I think Lutris is far too complicated. This makes implementing new features a bit harder.

**Comment by JoshuaFern** [comment]
I'm going to close this for now, we should partition anything of interest into their own discrete issues. #136

**Comment by sharkwouter** [comment]
True, I do much prefer that. Otherwise you get these half resolved issues which just get stuck. Thanks!
