### ISSUE TITLE
FTL is not detected after installation

### ISSUE THREAD

**Issue by sharkwouter** [sharkwouter/minigalaxy#14]
FTL doesn't have the expected start.sh script for starting it, which makes Minigalaxy unable to launch it or even see that it is installed.

**Comment by CharoSW** [comment]
Just as a confirmation it's definitely due to a missing start.sh? I have also found a game detection bug with FTL (mine does have a start.sh) and others not being detected but its due to the title of the game containing characters that the GOG installers don't use.  Adding those characters, for me they were colons and dashes, allowed them to be detected at next start up.

**Comment by sharkwouter** [comment]
Maybe I should have clarified this bug a little bit better. This is what I observed after installing FTL with Minigalaxy.

Whether games installed with the installer are detected would be a different issue. That's not something I've extensively tested, though, but I would like for it to work. Which games specifically did you see this with?

**Comment by CharoSW** [comment]
Ah, well in that case I'll just open a new issue because it's too different to track together

**Comment by sharkwouter** [comment]
I've added an error message for if games don't have a start.sh script.

**Comment by sharkwouter** [comment]
This will be resolved in the next release. FTL contains a file in the game directory called goggame-id.info which contains the binary to use. Minigalaxy now uses that.
