### ISSUE TITLE
Feature Request: Option "Download only"

### ISSUE THREAD

**Issue by AncientLich** [sharkwouter/minigalaxy#161]
I think that there should be an option that allows you to "download only" (not install) games (at least windows games).
Most of times you want to manage yourself wine prefixes and wine versions for a particular game.

It is not a big issue, to be honest: you can refuse to install Gog wine and delete the prefix; but, saying that, it could be nice if you can decide to avoid completely the install step.

**Comment by arrowgent** [comment]
agreed.  i download everything and set it up myself in my own locations including usually adding the game to steam.

along with download only, would be nice if the file names remained as GOG named them "setup_game_version2.000.exe" or whatever.   instead of how your downloader renames the files to generic game titles.

**Comment by cweiske** [comment]
I bought Horzion Zero Dawn and wanted to download the 72 GiB files onto my NAS as backup.
Doing that manually requires me to manually download 19 4GiB files, which is what I wanted to avoid by using minigalaxy.

For that use case, a download-only option would be very helpful.
Keeping the original file names would be nice, too.
Being able to select the download directory (thus storing the files on the spacious NAS instead of the limited laptop SSD) would also be nice.

**Comment by cweiske** [comment]
For now I use [lgogdownloader](https://github.com/Sude-/lgogdownloader):

    $ lgogdownloader --verbose --directory /mnt/nas/games/ --game horizon_zero_dawn_complete_edition --download

**Comment by sharkwouter** [comment]
Thanks for the report and the discussion which followed. I do feel like lgogdownloader is a bit better suited for this purpose.

**Comment by cweiske** [comment]
I'd say close it.
