### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by airon90** [sharkwouter/minigalaxy#17]
How can I translate this app?

**Comment by sharkwouter** [comment]
Currently I haven't implemented translation support yet. I would love to add it, though. I'll look into it.

**Comment by sharkwouter** [comment]
Translation support has been added in commit 3968cc61c90be839e1c8b5183629bca251fe9f66. I've added a Dutch translation, mostly for testing purposes. Minigalaxy will load a translation based on the system's locale.

I still need to write proper instructions on how to add translations, but I'll try to explain the process here. Translations can be added by forking this repo, creating the translation and creating a pull request with the translation you made. I'm going to assume you know how to fork a repo and make pull requests.

The process of creating a translation works like this:
- Find out the locale string of the language you'd like to add. For German this would be ``de_DE.UTF-8`` for instance. Take a look at ``/etc/locale.gen`` for a list. Do use UTF-8, though, otherwise special characters won't work (umlauts and ß for German for example).
- Create the translation file. This can be done with the script ``scripts/add-new-language.sh``. Use the locale string for your language with it to create the translation file. This would look like this: ``scripts/add-new-language.sh de_DE.UTF-8``
- Edit the translation file. It should open automatically after running the previous command. Otherwise you can find it in ``data/po``. The translation goes in the msgstr field.
- Compile the translation. This can be done by running ``scripts/compile-languages.sh``.
- Test the translation. You can run ``LC_ALL=de_DE.UTF-8 bin/minigalaxy`` to do so. Make sure the locale matches the one you chose and it is installed on your system.
- Add the new translation to ``setup.py``. Take a look at the data_files variable. Dutch (nl) is already there as an example.

After you've done that you can make a pull request. I would like to make this easier in the future, but I got translations working for the first time about an hour ago 😅. I hope that helps, let me know if you need any help :)

**Comment by airon90** [comment]
I'm glad you added this feature so rapidly! 😍 I would have waited for days and months if needed. Thank you very much! I will give it a try next year (got it? LOL). I will wait to add information on the README about how to translate, maybe you will change the mechanism. Thank you again for your hard work!

**Comment by sharkwouter** [comment]
Great! I've get on to writing instructions then. I probably should rename some of those scripts.

**Comment by sharkwouter** [comment]
For anyone following this issue, the instructions are in the wiki. They can be found here: https://github.com/sharkwouter/minigalaxy/wiki/Translating-Minigalaxy

I'll close this issue for now, because translation support is working well and we've had people contribute them. Any more translations or fixes to translations are welcome.
