### ISSUE TITLE
Tries to unzip .sh files (and fails)

### ISSUE THREAD

**Issue by Fluffkin** [sharkwouter/minigalaxy#226]
West of Loathing for an example. Click "update". Update downloads then...

```
Executing integrity check for /home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh
Verifying archive integrity... MD5 checksums are OK. All good.
[/home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of /home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh or
        /home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh.zip, and cannot find /home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh.ZIP, period.
Exception in thread Thread-91:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Failed to install West of Loathing: /home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh could not be unzipped.
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/minigalaxy/download.py", line 26, in finish
    self.__finish_func()
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/gametile.py", line 324, in __update
    install_success = self.__install(update=True)
  File "/usr/lib/python3.9/site-packages/minigalaxy/ui/gametile.py", line 290, in __install
    install_game(self.game, installer, main_window=self.parent.parent)
  File "/usr/lib/python3.9/site-packages/minigalaxy/installer.py", line 34, in install_game
    raise CannotOpenZipContent("{} could not be unzipped.".format(installer))
minigalaxy.installer.CannotOpenZipContent: /home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh could not be unzipped.
```
Happens .. which is not good when applying an update.

**Comment by makson96** [comment]
Thanks for the report.

I think that the real issue here is that something went wrong during installer download and that is the reason why it cannot be unzipped. You could manually remove "/home/zzzzz/.cache/minigalaxy/download/West of Loathing/west_of_loathing_1_11_11_11_11_41181.sh" and retry the update.

Issues with downloading are tracked here #191 

Nevertheless all exceptions should be handled, so I will take a look of this particular one too.

**Comment by sharkwouter** [comment]
Thanks for the report. I've seen this issue before, but I've not been able to reproduce it in a reliable way. The weirdest thing is that the fact that it is trying to unzip the game means that the checksum check has succeeded, so the contents of the archive should not be damaged.

What we might be able to use as a workaround is to just run the actual installer if this happens. That should be possible.

**Comment by makson96** [comment]
Hmm, this MD5 checksum pass makes it looks strange. First of all we should probably obtain installer which cause this issue to check:
- if we can do something with such an installer
- if its re-download helps

**Comment by Fluffkin** [comment]
There might be something else going wrong, re-downloading it doesn't help. If I go to the cache directory and try and run the installer I get...

```
Verifying archive integrity... All good.
Uncompressing West of Loathing (GOG.com)  100%  
Collecting info for this system...
Operating system: linux
CPU Arch: x86_64
trying mojosetup in bin/linux/x86_64
USING en_US



PANIC
  Initial setup failed. Cannot continue.


Error: Couldn't run mojosetup
```
Which is really weird. Archive seems fine, but for some reason the installer still won't run. Maybe it's a problem at the GOG end? Probably still worth catching and letting the user know something is wrong (whatever it is that actually is wrong?!) I've had it happen with another update as well but I forget which game that was.

**Comment by Odelpasso** [comment]
@makson96 , i think there is a big bug since the commit ffe09924a7b959514663d0e0d8d1b5d62041b315 (Merge pull request #212 from makson96/fix_208). I have the same issue when i want to install a Windows game : 
`Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/barbiturik/minigalaxy/minigalaxy/ui/gametile.py", line 269, in __install_game
    install_success = self.__install()
  File "/home/barbiturik/minigalaxy/minigalaxy/ui/gametile.py", line 288, in __install
    err_msg = install_game(self.game, installer)
  File "/home/barbiturik/minigalaxy/minigalaxy/installer.py", line 17, in install_game
    error_message = extract_installer(game, installer, tmp_dir)
  File "/home/barbiturik/minigalaxy/minigalaxy/installer.py", line 73, in extract_installer
    process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: 'WINEPREFIX=/home/barbiturik/GOG Games/Horizon Zero Dawn Complete Edition/prefix'
`
If I use Minigalaxy before this commit, it works.
Cheers

**Comment by Odelpasso** [comment]
Way to reproduce : 
1- download a game for the 1st time. When Minigalaxy must to launch command = [WINEPREFIX={}.format(prefix), wine, installer, ... ], nothing happen.

2- When i move the Windows setup to « install_dir/keep_install_dir », launch MiniGalaxy and install the game, i have the error message like in my last message
