### ISSUE TITLE
Wine

### ISSUE THREAD

**Issue by Fargotroniac** [sharkwouter/minigalaxy#415]
Hi,

This is not a mistake, it's just a question.

I noticed that Wine is installed automatically with this software. What version does it use? Will there be automatic wine updates? So as if I installed wine directly on the system (https://wiki.winehq.org/Ubuntu) and an update was released?

Or is it better to install wine according to the given link (for use outside MiniGalaxy) and MiniGalaxy will then use this wine? 

Thank you

**Comment by sharkwouter** [comment]
It uses the ``wine`` command. So if you have a wine command in your ``PATH``, that will be used. That's usually the version your package manager installed.

Wine is a recommended package for Minigalaxy, so if you have apt configured to install recommended packages it will be installed.

**Comment by Fargotroniac** [comment]
Ok, thank you.

And do you plane release program on Flathub or ppa for "automatic" updating?

**Comment by sharkwouter** [comment]
Minigalaxy is already of Flathub and it supports running Windows games there. It's also packaged in most distributions. Ubuntu 21.04 will have Minigalaxy 1.1.0.

I'm going to close this issue for now, though, since I think your questions have been answered. Thanks for asking, though. If you'd like to discuss further you can either just reply, reopen or join us on discord.
