### ISSUE TITLE
1.2.0 AppData validation fails

### ISSUE THREAD

**Issue by tim77** [sharkwouter/minigalaxy#518]
```
+ appstream-util validate-relax --nonet /builddir/build/BUILDROOT/minigalaxy-1.2.0-1.fc37.x86_64/usr/share/metainfo/io.github.sharkwouter.Minigalaxy.metainfo.xml
/builddir/build/BUILDROOT/minigalaxy-1.2.0-1.fc37.x86_64/usr/share/metainfo/io.github.sharkwouter.Minigalaxy.metainfo.xml: FAILED:
? tag-invalid           : <release> versions are not in order [0.9.0 before 1.2.0]
Validation of files failed
```

**Comment by sharkwouter** [comment]
Okay, that sucks. I'm sorry for that. I automated the release and the creation of some files, like the metadata file, since it is so much effort to update the changelog in 3 different places every time. The following script adds the release to the metadata file: https://github.com/sharkwouter/minigalaxy/blob/master/scripts/create-release.sh

I wasn't able to get xml_starlet to do the ordering correctly unfortunately. I'm sorry about that. Maybe someone else has a solution.

**Comment by sharkwouter** [comment]
Okay, I found out how to sort it now. I'll do a new release :/

**Comment by sharkwouter** [comment]
@tim77 does the 1.2.1 release fix this issue? I've adapted the script a bit now.

**Comment by tim77** [comment]
Still not proper order `? tag-invalid           : <release> versions are not in order [1.2.0 before 1.2.1]`

**Comment by sharkwouter** [comment]
Oh no

**Comment by sharkwouter** [comment]
I'll make a branch for you and fix it tomorrow 😬

**Comment by sharkwouter** [comment]
Can you try the 1.2.1-flathub tag?

**Comment by tim77** [comment]
@sharkwouter `1.2.1-flathub` works. Thank you! Building...

**Comment by sharkwouter** [comment]
Finally, thanks!
